# Generated by Django 4.2.7 on 2023-12-01 10:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WebDev", "Web Dev"),
                            ("AI", "AI"),
                            ("Bash Scripting", "Bash Scripting"),
                            ("Web Scraping", "Web Scraping"),
                            ("Django/Flask", "Django/Flask"),
                            ("Python", "Python"),
                            ("JS/React", "JS/React"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("post_author", models.CharField(default="Abdulahi", max_length=100)),
                (
                    "post_author_url",
                    models.URLField(default="https://twitter.com/SDecipherer"),
                ),
                (
                    "post_title",
                    models.CharField(max_length=250, verbose_name="Blog Title"),
                ),
                ("post_date", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("post_content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("image_thumbnail", models.ImageField(upload_to="blog_thumbnails/")),
                ("send_post_to_subscribers", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-updated", "-post_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("graduation_year", models.PositiveIntegerField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "subscription_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
            options={
                "ordering": ["-subscription_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("project_image", models.ImageField(upload_to="projects/")),
                ("poster_image", models.ImageField(upload_to="projects/poster/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WebDev", "Web Dev"),
                            ("AI", "AI"),
                            ("Bash Scripting", "Bash Scripting"),
                            ("Web Scraping", "Web Scraping"),
                            ("Django/Flask", "Django/Flask"),
                            ("Python", "Python"),
                            ("JS/React", "JS/React"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posted_date", models.DateField()),
                ("live_project_link", models.URLField(blank=True, null=True)),
                ("github_repo_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("profile_picture", models.ImageField(upload_to="images/")),
                ("favicon", models.ImageField(upload_to="images/")),
                ("introduction", models.TextField()),
                ("cv_link", models.FileField(upload_to="documents/")),
                ("twitter_link", models.URLField(blank=True, null=True)),
                ("linkedin_link", models.URLField(blank=True, null=True)),
                ("facebook_link", models.URLField(blank=True, null=True)),
                ("whatsapp_link", models.URLField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
                ("header_title", models.CharField(max_length=100)),
                ("header_description", models.TextField()),
                ("header_keywords", models.TextField()),
                ("education", models.ManyToManyField(to="portfoliov2.education")),
                ("internship", models.ManyToManyField(to="portfoliov2.internship")),
                ("tech_stack", models.ManyToManyField(to="portfoliov2.techstack")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blog_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="portfoliov2.blogpost",
                    ),
                ),
            ],
        ),
    ]
