# Generated by Django 4.2.7 on 2023-12-02 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
