# Generated by Django 4.2.7 on 2023-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfoliov2",
            "0002_rename_headder_description_personalinfo_header_description",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WebDev", "Web Dev"),
                            ("AI", "AI"),
                            ("Bash Scripting", "Bash Scripting"),
                            ("Web Scraping", "Web Scraping"),
                            ("Django/Flask", "Django/Flask"),
                            ("Python", "Python"),
                            ("JS/React", "JS/React"),
                            ("Others", "Others"),
                        ],
                        max_length=100,
                    ),
                ),
                ("post_title", models.CharField(max_length=200)),
                ("post_date", models.DateTimeField()),
                ("post_content", models.TextField()),
                ("image_thumbnail", models.ImageField(upload_to="blog_thumbnails/")),
            ],
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("project_image", models.ImageField(upload_to="projects/")),
                ("poster_image", models.ImageField(upload_to="projects/poster/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WebDev", "Web Dev"),
                            ("AI", "AI"),
                            ("Bash Scripting", "Bash Scripting"),
                            ("Web Scraping", "Web Scraping"),
                            ("Django/Flask", "Django/Flask"),
                            ("Python", "Python"),
                            ("JS/React", "JS/React"),
                            ("Others", "Others"),
                        ],
                        max_length=20,
                    ),
                ),
                ("posted_date", models.DateField()),
                ("live_project_link", models.URLField(blank=True, null=True)),
                ("github_repo_link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="facebook_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="twitter_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="whatsapp_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
