# Generated by Django 4.2.7 on 2023-12-02 20:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0002_delete_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
