# Generated by Django 4.2.7 on 2023-12-03 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0003_alter_comment_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="education",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="internship",
        ),
        migrations.RemoveField(
            model_name="personalinfo",
            name="tech_stack",
        ),
        migrations.AddField(
            model_name="education",
            name="personal_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="portfoliov2.personalinfo",
            ),
        ),
        migrations.AddField(
            model_name="techstack",
            name="personal_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tech_stacks",
                to="portfoliov2.personalinfo",
            ),
        ),
        migrations.DeleteModel(
            name="Internship",
        ),
        migrations.AddField(
            model_name="workexperience",
            name="personal_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="work_experiences",
                to="portfoliov2.personalinfo",
            ),
        ),
    ]
