# Generated by Django 4.2.7 on 2023-11-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0003_blogpost_contactmessage_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
