# Generated by Django 4.2.7 on 2023-12-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0004_workexperience_remove_personalinfo_education_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="personal_info",
        ),
        migrations.RemoveField(
            model_name="techstack",
            name="personal_info",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="personal_info",
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="education",
            field=models.ManyToManyField(to="portfoliov2.education"),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="tech_stack",
            field=models.ManyToManyField(to="portfoliov2.techstack"),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="work_experience",
            field=models.ManyToManyField(to="portfoliov2.workexperience"),
        ),
    ]
