# Generated by Django 4.2.7 on 2023-12-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0005_remove_education_personal_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="downvotes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="upvotes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
