# Generated by Django 4.2.7 on 2023-11-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0005_blogpost_post_author_blogpost_post_author_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="post_author",
            field=models.CharField(default="Abdulahi", max_length=100),
        ),
    ]
