# Generated by Django 4.2.7 on 2023-11-09 04:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0006_alter_blogpost_post_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="post_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="post_title",
            field=models.CharField(max_length=250, verbose_name="Blog Title"),
        ),
    ]
