# Generated by Django 4.2.7 on 2023-11-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfoliov2", "0007_alter_blogpost_post_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "subscription_date",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
            ],
            options={
                "ordering": ["-subscription_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="blogpost",
            options={"ordering": ["-updated", "-post_date"]},
        ),
        migrations.AddField(
            model_name="blogpost",
            name="send_post_to_subscribers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
